# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b3c226ebe5e1a193977d41603f5322d5884e4f472fe5caea22c756034b22a939d77699d226ec9e00230d167486549d6788022d957dc5b8a74c4cdb0e5da323a

test:
  secret_key_base: c344f6506c917d866ac9622b03a7ea012f898043d69a676b7fed6719a89de17a2402e748d33ff0bcc8f334a7a03bb1566ead98bd8651711213d193a37c809383

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
